@startuml

SIP_Router -> ServiceBroker: SIP OPTIONS
ServiceBroker -> AS1_endpoint_1: SIP OPTIONS
ServiceBroker <-- AS1_endpoint_1: 200 OK

ServiceBroker -> AS2_endpoint_1: SIP OPTIONS
ServiceBroker <-- AS2_endpoint_1: 480 (Temporary Unavailable)

ServiceBroker -> AS2_endpoint_2: SIP OPTIONS
ServiceBroker <-- AS2_endpoint_2: 480 (Temporary Unavailable)

ServiceBroker -> AS2_endpoint_3: SIP OPTIONS
ServiceBroker <-- AS2_endpoint_3: 480 (Temporary Unavailable)

SIP_Router <-- ServiceBroker: 480 (Temporary Unavailable)

@enduml